import crypto from "crypto";
import bcrypt from "bcryptjs";
import { NextResponse } from "next/server";

import prisma from "@/lib/prisma";

export const runtime = "nodejs";

const MIN_PASSWORD_LENGTH = 8;

const INVALID_TOKEN_MESSAGE =
  "This password reset link is invalid or has expired.";

const SUCCESS_MESSAGE =
  "Your password has been reset successfully.";

function hashToken(token: string) {
  return crypto
    .createHash("sha256")
    .update(token)
    .digest("hex");
}

export async function POST(request: Request) {
  try {
    /*
     * ==========================================================
     * 1. READ REQUEST BODY
     * ==========================================================
     */

    let body: unknown;

    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        {
          success: false,
          message: "Invalid request.",
        },
        {
          status: 400,
        }
      );
    }

    if (
      typeof body !== "object" ||
      body === null ||
      !("token" in body) ||
      !("password" in body) ||
      !("confirmPassword" in body) ||
      typeof body.token !== "string" ||
      typeof body.password !== "string" ||
      typeof body.confirmPassword !== "string"
    ) {
      return NextResponse.json(
        {
          success: false,
          message: "Invalid request.",
        },
        {
          status: 400,
        }
      );
    }

    const token = body.token.trim();
    const password = body.password;
    const confirmPassword = body.confirmPassword;

    /*
     * ==========================================================
     * 2. BASIC VALIDATION
     * ==========================================================
     */

    if (!token) {
      return NextResponse.json(
        {
          success: false,
          message: INVALID_TOKEN_MESSAGE,
        },
        {
          status: 400,
        }
      );
    }

    if (token.length !== 64) {
      return NextResponse.json(
        {
          success: false,
          message: INVALID_TOKEN_MESSAGE,
        },
        {
          status: 400,
        }
      );
    }

    /*
     * The token generated by forgot-password is a 32-byte
     * random value encoded as hexadecimal.
     *
     * 32 bytes = 64 hexadecimal characters.
     */

    if (!/^[a-f0-9]{64}$/i.test(token)) {
      return NextResponse.json(
        {
          success: false,
          message: INVALID_TOKEN_MESSAGE,
        },
        {
          status: 400,
        }
      );
    }

    if (password.length < MIN_PASSWORD_LENGTH) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Password must be at least 8 characters long.",
        },
        {
          status: 400,
        }
      );
    }

    if (password !== confirmPassword) {
      return NextResponse.json(
        {
          success: false,
          message: "Passwords do not match.",
        },
        {
          status: 400,
        }
      );
    }

    /*
     * ==========================================================
     * 3. HASH RAW TOKEN
     * ==========================================================
     *
     * The raw token exists only in the reset URL.
     *
     * The database stores SHA-256(token), not the usable token.
     */

    const tokenHash = hashToken(token);

    /*
     * ==========================================================
     * 4. FIND RESET TOKEN
     * ==========================================================
     *
     * We require:
     *
     * - matching token hash
     * - token not already used
     *
     * Expiry is checked separately below.
     */

    const resetToken =
      await prisma.passwordResetToken.findUnique({
        where: {
          tokenHash,
        },
        select: {
          id: true,
          userId: true,
          expiresAt: true,
          usedAt: true,
        },
      });

    /*
     * ==========================================================
     * 5. INVALID / USED TOKEN
     * ==========================================================
     */

    if (!resetToken || resetToken.usedAt) {
      return NextResponse.json(
        {
          success: false,
          message: INVALID_TOKEN_MESSAGE,
        },
        {
          status: 400,
        }
      );
    }

    /*
     * ==========================================================
     * 6. EXPIRY CHECK
     * ==========================================================
     */

    const now = new Date();

    if (resetToken.expiresAt <= now) {
      /*
       * Mark the expired token as consumed so it cannot
       * continue to be considered active.
       */

      await prisma.passwordResetToken.updateMany({
        where: {
          id: resetToken.id,
          usedAt: null,
        },
        data: {
          usedAt: now,
        },
      });

      return NextResponse.json(
        {
          success: false,
          message: INVALID_TOKEN_MESSAGE,
        },
        {
          status: 400,
        }
      );
    }

    /*
     * ==========================================================
     * 7. VERIFY USER
     * ==========================================================
     */

    const user = await prisma.user.findUnique({
      where: {
        id: resetToken.userId,
      },
      select: {
        id: true,
      },
    });

    if (!user) {
      /*
       * Do not reveal internal account/database information.
       */

      await prisma.passwordResetToken.updateMany({
        where: {
          id: resetToken.id,
          usedAt: null,
        },
        data: {
          usedAt: now,
        },
      });

      return NextResponse.json(
        {
          success: false,
          message: INVALID_TOKEN_MESSAGE,
        },
        {
          status: 400,
        }
      );
    }

    /*
     * ==========================================================
     * 8. HASH NEW PASSWORD
     * ==========================================================
     *
     * Never store a plain-text password.
     *
     * bcrypt generates its own salt and stores the resulting
     * password hash.
     */

    const passwordHash = await bcrypt.hash(
      password,
      12
    );

    /*
     * ==========================================================
     * 9. ATOMIC PASSWORD RESET
     * ==========================================================
     *
     * The password update and token consumption happen inside
     * one database transaction.
     *
     * The conditional update of the token ensures that a token
     * already consumed by another request cannot be reused.
     */

    const result = await prisma.$transaction(
      async (transaction) => {
        const consumedToken =
          await transaction.passwordResetToken.updateMany({
            where: {
              id: resetToken.id,
              userId: resetToken.userId,
              tokenHash,
              usedAt: null,
              expiresAt: {
                gt: new Date(),
              },
            },
            data: {
              usedAt: new Date(),
            },
          });

        if (consumedToken.count !== 1) {
          return {
            success: false as const,
          };
        }

        await transaction.user.update({
          where: {
            id: resetToken.userId,
          },
          data: {
            password: passwordHash,
          },
        });

        /*
         * Invalidate every other currently active reset token
         * for this account.
         *
         * This protects against older reset links remaining
         * usable after the password has been changed.
         */

        await transaction.passwordResetToken.updateMany({
          where: {
            userId: resetToken.userId,
            id: {
              not: resetToken.id,
            },
            usedAt: null,
          },
          data: {
            usedAt: new Date(),
          },
        });

        return {
          success: true as const,
        };
      }
    );

    /*
     * ==========================================================
     * 10. CONCURRENT / RACE-CONDITION PROTECTION
     * ==========================================================
     */

    if (!result.success) {
      return NextResponse.json(
        {
          success: false,
          message: INVALID_TOKEN_MESSAGE,
        },
        {
          status: 400,
        }
      );
    }

    /*
     * ==========================================================
     * 11. SUCCESS
     * ==========================================================
     *
     * Never return:
     *
     * - raw token
     * - token hash
     * - password hash
     * - user database record
     * - internal database information
     */

    return NextResponse.json(
      {
        success: true,
        message: SUCCESS_MESSAGE,
      },
      {
        status: 200,
      }
    );
  } catch (error) {
    /*
     * ==========================================================
     * 12. UNEXPECTED SERVER ERROR
     * ==========================================================
     *
     * Detailed error is logged server-side only.
     * Internal infrastructure details are never sent to users.
     */

    console.error(
      "RESET PASSWORD ERROR:",
      error
    );

    return NextResponse.json(
      {
        success: false,
        message:
          "Unable to reset your password right now. Please request a new reset link and try again.",
      },
      {
        status: 500,
      }
    );
  }
}